# -*- coding: UTF-8 -*-
# ------------------------------------------------------------------------------
#     Generated by TYPETR-Assistant MasterDataManager
# ..............................................................................
#
#   masterData.py
#
from assistantLib.assistantModules.data import MasterData as MD

MASTERS_DATA = {
	'Upgrade_Try-Bold': MD(
		name='Upgrade_Try-Bold',
		ufoPath='ufo-try/Upgrade_Try-Bold.ufo',
		#	Angles
		italicAngle=0,
		#	Vertical metrics
		ascender=748,
		capHeight=658,
		xHeight=474,
		descender=-252,
		baseOvershoot=14,
		capOvershoot=17,
		scOvershoot=14,
		supsOvershoot=10,
		#	Info
		copyright='(c) 2017 TYPETR Petr van Blokland (buro@petr.com) Original Design. ',
	),

	'Upgrade_Try-Bold_Italic': MD(
		name='Upgrade_Try-Bold_Italic',
		ufoPath='ufo-try/Upgrade_Try-Bold_Italic.ufo',
		#	Angles
		italicAngle=-8,
		#	Vertical metrics
		ascender=748,
		capHeight=658,
		xHeight=474,
		descender=-252,
		baseOvershoot=14,
		capOvershoot=16,
		scOvershoot=14,
		supsOvershoot=10,
		#	Info
		copyright='Copyright for Upgrade Try',
	),

	'Upgrade_Try-Hairline': MD(
		name='Upgrade_Try-Hairline',
		ufoPath='ufo-try/Upgrade_Try-Hairline.ufo',
		#	Angles
		italicAngle=0,
		#	Vertical metrics
		ascender=748,
		capHeight=658,
		xHeight=462,
		descender=-252,
		baseOvershoot=8,
		capOvershoot=8,
		scOvershoot=8,
		supsOvershoot=6,
		#	Info
		copyright='(c) 2017 TYPETR Petr van Blokland (buro@petr.com) Original Design. ',
	),

	'Upgrade_Try-Hairline_Italic': MD(
		name='Upgrade_Try-Hairline_Italic',
		ufoPath='ufo-try/Upgrade_Try-Hairline_Italic.ufo',
		#	Angles
		italicAngle=-8,
		#	Vertical metrics
		ascender=748,
		capHeight=658,
		xHeight=462,
		descender=-252,
		baseOvershoot=8,
		capOvershoot=8,
		scOvershoot=8,
		supsOvershoot=6,
		#	Info
		copyright='Copyright for Upgrade Try',
	),

	'Upgrade_Try-Light': MD(
		name='Upgrade_Try-Light',
		ufoPath='ufo-try/Upgrade_Try-Light.ufo',
		#	Angles
		italicAngle=0,
		#	Vertical metrics
		ascender=748,
		capHeight=658,
		xHeight=462,
		descender=-252,
		baseOvershoot=10,
		capOvershoot=14,
		scOvershoot=10,
		supsOvershoot=8,
		#	Info
		copyright='(c) 2017 TYPETR Petr van Blokland (buro@petr.com) Original Design. ',
	),

	'Upgrade_Try-Light_Italic': MD(
		name='Upgrade_Try-Light_Italic',
		ufoPath='ufo-try/Upgrade_Try-Light_Italic.ufo',
		#	Angles
		italicAngle=-8,
		#	Vertical metrics
		ascender=748,
		capHeight=658,
		xHeight=462,
		descender=-252,
		baseOvershoot=10,
		capOvershoot=14,
		scOvershoot=10,
		supsOvershoot=8,
		#	Info
		copyright='Copyright for Upgrade Try',
	),

	'Upgrade_Try-Regular': MD(
		name='Upgrade_Try-Regular',
		ufoPath='ufo-try/Upgrade_Try-Regular.ufo',
		#	Angles
		italicAngle=0,
		#	Vertical metrics
		ascender=748,
		capHeight=658,
		xHeight=466,
		descender=-252,
		baseOvershoot=11,
		capOvershoot=15,
		scOvershoot=11,
		supsOvershoot=8,
		#	Info
		copyright='(c) 2017 TYPETR Petr van Blokland (buro@petr.com) Original Design. ',
	),

	'Upgrade_Try-Regular_Italic': MD(
		name='Upgrade_Try-Regular_Italic',
		ufoPath='ufo-try/Upgrade_Try-Regular_Italic.ufo',
		#	Angles
		italicAngle=-8,
		#	Vertical metrics
		ascender=748,
		capHeight=658,
		xHeight=466,
		descender=-252,
		baseOvershoot=11,
		capOvershoot=15,
		scOvershoot=11,
		supsOvershoot=8,
		#	Info
		copyright='Copyright for Upgrade Try',
	),

	'Upgrade_Try-UltraBlack': MD(
		name='Upgrade_Try-UltraBlack',
		ufoPath='ufo-try/Upgrade_Try-UltraBlack.ufo',
		#	Angles
		italicAngle=0,
		#	Vertical metrics
		ascender=748,
		capHeight=658,
		xHeight=502,
		descender=-252,
		baseOvershoot=24,
		capOvershoot=18,
		scOvershoot=24,
		supsOvershoot=18,
		#	Info
		copyright='(c) 2017 TYPETR Petr van Blokland (buro@petr.com) Original Design. ',
	),

	'Upgrade_Try-UltraBlack_Italic': MD(
		name='Upgrade_Try-UltraBlack_Italic',
		ufoPath='ufo-try/Upgrade_Try-UltraBlack_Italic.ufo',
		#	Angles
		italicAngle=-7.96,
		#	Vertical metrics
		ascender=748,
		capHeight=658,
		xHeight=502,
		descender=-252,
		baseOvershoot=24,
		capOvershoot=18,
		scOvershoot=24,
		supsOvershoot=18,
		#	Info
		copyright='Copyright for Upgrade Try',
	),

}

