# -*- coding: UTF-8 -*-
# ------------------------------------------------------------------------------
#     Generated by TYPETR-Assistant MasterDataManager
# ..............................................................................
#
#   masterData.py
#
from assistantLib.assistantModules.data import MasterData as MD

MASTERS_DATA = {
    'Upgrade_Try-Bold': MD(
        name='Upgrade_Try-Bold',
        ufoPath='ufo/Upgrade_Try-Bold.ufo',
        #	Angles
        italicAngle=0,
        #	Vertical metrics
        ascender=750,
        capHeight=750,
        xHeight=500,
        descender=-250,
        baseOvershoot=12,
        capOvershoot=12,
        scOvershoot=12,
        supsOvershoot=9,
        #	Info
        copyright='',
	),

    'Upgrade_Try-Light': MD(
        name='Upgrade_Try-Light',
        ufoPath='ufo/Upgrade_Try-Light.ufo',
        #	Angles
        italicAngle=0,
        #	Vertical metrics
        ascender=750,
        capHeight=750,
        xHeight=500,
        descender=-250,
        baseOvershoot=12,
        capOvershoot=12,
        scOvershoot=12,
        supsOvershoot=9,
        #	Info
        copyright='',
	),

    'Upgrade_Try-Regular': MD(
        name='Upgrade_Try-Regular',
        ufoPath='ufo/Upgrade_Try-Regular.ufo',
        #	Angles
        italicAngle=0,
        #	Vertical metrics
        ascender=750,
        capHeight=750,
        xHeight=500,
        descender=-250,
        baseOvershoot=12,
        capOvershoot=12,
        scOvershoot=12,
        supsOvershoot=9,
        #	Info
        copyright='',
	),

}

